TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.0
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.4
  acc_lim_x: 1.0
  acc_lim_theta: 1.0
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.2
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  occdist_scale: 0.05